@startuml
title oscript.web - Deployment
caption Диаграмма развертывания с проверкой доступности
node "Github Releases" <<AmazonS3>> as 6 {
  artifact "jsondatabase" <<Container>> as 9
}
node "Heroku Application" <<micro-instance>> as 5 {
  node "ASP.NET Application" <<Docker>> as 7 {
    artifact "hub.oscript.io" <<Container>> as 8
  }
}
8 ..> 9 : Только чтение <<JSONRead>>
@enduml

