name: Публикация документации в виде артефакта ночной сборки

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Публикация документа
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Electronic Signature
        uses: shrink/actions-document-sign@v1
        id: create-signature
      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: '${{ steps.create-signature.outputs.signature }} ./OMYGod.md'
      - name: Rename Artifact
        run: |
          cp "${{ steps.publish-document.outputs.pdf }}" "./OMYGod-NigthBuild.pdf"
          cp "${{ steps.create-signature.outputs.signature }}" "./AlexeyLustin.signature"
      - name: Upload Document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: 'OMyGod.zip'
          path: |
            "**/AlexeyLustin*.signature"
            "**/OMYGod-*.pdf"
          retention-days: 14
